name: Generate SVM IDL artifacts
inputs:
  type:
    description: "Type of the artifacts, used in archive name"
    required: true
  path:
    description: "Paths to archive for caching"
    required: true
  node_version:
    description: "Node version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Use Node ${{ inputs.node_version }}"
      uses: ./.github/actions/setup-node-if-needed
      with:
        node_version: ${{ inputs.node_version }}
    - name: Setup Anchor & Solana
      uses: ./.github/actions/setup-solana-anchor
      with:
        node_version: ${{ inputs.node_version }}
    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@v2
    - name: Install packages
      shell: bash
      run: yarn install --frozen-lockfile --ignore-optional
    - name: Generate SVM IDL artifacts
      shell: bash
      run: yarn generate-svm-artifacts
    - name: Archive SVM IDL artifacts (for caching)
      shell: bash
      env:
        CACHE_PATHS: ${{ inputs.path }}
      run: echo "$CACHE_PATHS" | xargs tar -cf svm-${{ inputs.type }}.tar
