name: Generate EVM artifacts
inputs:
  path:
    description: "Paths to archive for caching"
    required: true
  node_version:
    description: "Node version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Use Node ${{ inputs.node_version }}"
      uses: ./.github/actions/setup-node-if-needed
      with:
        node_version: ${{ inputs.node_version }}
    - name: Install packages
      shell: bash
      run: yarn install --frozen-lockfile
    - name: Build Hardhat
      shell: bash
      run: yarn build-evm
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
    - name: Install forge dependencies
      shell: bash
      run: forge install
    - name: Build Foundry
      shell: bash
      run: forge build --skip test script
    - name: Generate Typechain
      shell: bash
      run: npx typechain --target ethers-v5 "out/!(build-info)/**/+([a-zA-Z0-9_]).json" --out-dir typechain
    - name: Archive EVM artifacts (for caching)
      shell: bash
      env:
        CACHE_PATHS: ${{ inputs.path }}
      run: echo "$CACHE_PATHS" | xargs tar -cf evm-artifacts.tar
