name: Generate EVM artifacts
inputs:
  node_version:
    description: "Node version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Use Node ${{ inputs.node_version }}"
      uses: actions/setup-node@v3
      with:
        node-version: "${{ inputs.node_version }}"
        cache: yarn
    - name: Install packages
      shell: bash
      run: yarn install --frozen-lockfile
    - name: Build EVM
      shell: bash
      run: yarn build-evm
