/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { AddressWhitelistInterface, AddressWhitelistInterfaceInterface } from "../AddressWhitelistInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "newElement",
        type: "address",
      },
    ],
    name: "addToWhitelist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getWhitelist",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newElement",
        type: "address",
      },
    ],
    name: "isOnWhitelist",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newElement",
        type: "address",
      },
    ],
    name: "removeFromWhitelist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class AddressWhitelistInterface__factory {
  static readonly abi = _abi;
  static createInterface(): AddressWhitelistInterfaceInterface {
    return new utils.Interface(_abi) as AddressWhitelistInterfaceInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): AddressWhitelistInterface {
    return new Contract(address, _abi, signerOrProvider) as AddressWhitelistInterface;
  }
}
