/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { MaticToken, MaticTokenInterface } from "../MaticToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class MaticToken__factory {
  static readonly abi = _abi;
  static createInterface(): MaticTokenInterface {
    return new utils.Interface(_abi) as MaticTokenInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): MaticToken {
    return new Contract(address, _abi, signerOrProvider) as MaticToken;
  }
}
