name: Setup Solana and Anchor
inputs:
  verify_version:
    description: "Solana verify version to install (leave empty to skip)"
    required: false
    default: ""
  node_version:
    description: "Node version to install"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Use Node ${{ inputs.node_version }}"
      uses: ./.github/actions/setup-node-if-needed
      with:
        node_version: ${{ inputs.node_version }}
    - name: Extract Solana versions
      uses: solana-developers/github-actions/extract-versions@v0.2.5
      id: versions
    - name: Setup Anchor & Solana
      uses: solana-developers/github-actions/setup-all@v0.2.5
      with:
        anchor_version: ${{ steps.versions.outputs.anchor_version }}
        solana_version: ${{ steps.versions.outputs.solana_version }}
        verify_version: ${{ inputs.verify_version }}
