export declare const amountToSeedWallets: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const amountToLp: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const amountToDeposit: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const amountToRelay: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const depositRelayerFeePct: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const modifiedRelayerFeePct: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const incorrectModifiedRelayerFeePct: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const realizedLpFeePct: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const oneHundredPct: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const totalPostFeesPct: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const totalPostModifiedFeesPct: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const amountToRelayPreFees: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const amountToRelayPreModifiedFees: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const destinationChainId = 1337;
export declare const originChainId = 666;
export declare const repaymentChainId = 777;
export declare const firstDepositId = 0;
export declare const depositQuoteTimeBuffer: number;
export declare const bondAmount: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const finalFee: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const finalFeeUsdc: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const totalBond: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const refundProposalLiveness = 7200;
export declare const zeroAddress = "0x0000000000000000000000000000000000000000";
export declare const zeroBytes32 = "0x0000000000000000000000000000000000000000000000000000000000000000";
export declare const identifier: string;
export declare const zeroRawValue: {
  rawValue: string;
};
export declare const mockBundleEvaluationBlockNumbers: number[];
export declare const mockPoolRebalanceLeafCount = 5;
export declare const mockPoolRebalanceRoot: string;
export declare const mockRelayerRefundRoot: string;
export declare const mockSlowRelayRoot: string;
export declare const amountHeldByPool: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const amountToReturn: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const mockTreeRoot: string;
export declare const sampleL2Gas = 5000000;
export declare const sampleL2MaxSubmissionCost: import("@ethersproject/bignumber/lib/bignumber").BigNumber;
export declare const sampleL2GasPrice = 10000000000;
