/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IdentifierWhitelistInterfaceInterface extends ethers.utils.Interface {
  functions: {
    "addSupportedIdentifier(bytes32)": FunctionFragment;
    "isIdentifierSupported(bytes32)": FunctionFragment;
    "removeSupportedIdentifier(bytes32)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addSupportedIdentifier", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "isIdentifierSupported", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "removeSupportedIdentifier", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "addSupportedIdentifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isIdentifierSupported", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeSupportedIdentifier", data: BytesLike): Result;

  events: {};
}

export class IdentifierWhitelistInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IdentifierWhitelistInterfaceInterface;

  functions: {
    addSupportedIdentifier(
      identifier: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isIdentifierSupported(identifier: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    removeSupportedIdentifier(
      identifier: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addSupportedIdentifier(
    identifier: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isIdentifierSupported(identifier: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  removeSupportedIdentifier(
    identifier: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addSupportedIdentifier(identifier: BytesLike, overrides?: CallOverrides): Promise<void>;

    isIdentifierSupported(identifier: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    removeSupportedIdentifier(identifier: BytesLike, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addSupportedIdentifier(
      identifier: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isIdentifierSupported(identifier: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    removeSupportedIdentifier(
      identifier: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addSupportedIdentifier(
      identifier: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isIdentifierSupported(identifier: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeSupportedIdentifier(
      identifier: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
