/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PolygonTokenBridgerInterface extends ethers.utils.Interface {
  functions: {
    "destination()": FunctionFragment;
    "l1Weth()": FunctionFragment;
    "maticToken()": FunctionFragment;
    "retrieve(address)": FunctionFragment;
    "send(address,uint256,bool)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "destination", values?: undefined): string;
  encodeFunctionData(functionFragment: "l1Weth", values?: undefined): string;
  encodeFunctionData(functionFragment: "maticToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "retrieve", values: [string]): string;
  encodeFunctionData(functionFragment: "send", values: [string, BigNumberish, boolean]): string;

  decodeFunctionResult(functionFragment: "destination", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "l1Weth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maticToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "retrieve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;

  events: {};
}

export class PolygonTokenBridger extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PolygonTokenBridgerInterface;

  functions: {
    destination(overrides?: CallOverrides): Promise<[string]>;

    l1Weth(overrides?: CallOverrides): Promise<[string]>;

    maticToken(overrides?: CallOverrides): Promise<[string]>;

    retrieve(token: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    send(
      token: string,
      amount: BigNumberish,
      isMatic: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  destination(overrides?: CallOverrides): Promise<string>;

  l1Weth(overrides?: CallOverrides): Promise<string>;

  maticToken(overrides?: CallOverrides): Promise<string>;

  retrieve(token: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  send(
    token: string,
    amount: BigNumberish,
    isMatic: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    destination(overrides?: CallOverrides): Promise<string>;

    l1Weth(overrides?: CallOverrides): Promise<string>;

    maticToken(overrides?: CallOverrides): Promise<string>;

    retrieve(token: string, overrides?: CallOverrides): Promise<void>;

    send(token: string, amount: BigNumberish, isMatic: boolean, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    destination(overrides?: CallOverrides): Promise<BigNumber>;

    l1Weth(overrides?: CallOverrides): Promise<BigNumber>;

    maticToken(overrides?: CallOverrides): Promise<BigNumber>;

    retrieve(token: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    send(
      token: string,
      amount: BigNumberish,
      isMatic: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    destination(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    l1Weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maticToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    retrieve(token: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    send(
      token: string,
      amount: BigNumberish,
      isMatic: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
